### ISSUE TITLE
Not "updating"....

### ISSUE THREAD

**Issue by mkmer** [jdeath/maytag_dryer_homeassistant#1]
When initially connected, the device was updating, then after some period it stops updating, remains in READY state.
Reviewing the code, it feels like we are missing the heartbeat logic on the HA side to detect a connection drop and need to reconnect.  I'm not super up to speed on HA state machines, but in the few integrations I have looked at, they seem to have heartbeat timers....

**Comment by jdeath** [comment]
Doing that correctly is probably beyond my skills. This has a basic heartbeat, where if it loses authorization or the api request fails, it will try to reauthorize 5 times before giving up.  I am not sure how to detect a loss of connection without that. In your testing, is there an attribute that gets a wonky value if it has a connection drop? I could try to detect that and trigger the reauthorization loop. The READY state is the normal state when not in use, so that will not work.

**Comment by mkmer** [comment]
You and me both :)  I'm more of a "discoverer" than a proper Python/HA software guy...

I have added a few diagnostic counters to try and figure out why it stopped updating.  I suspected the socket disconnected and/or HA stopped the update process.  If it gets "stuck" again, I'll should have a clearer picture of what happened (hopefully)

Thanks for the work on this, It's thankless sometimes :)

**Comment by mkmer** [comment]
It became "hung" again - I added an update counter to clearly show if the update function is being called, and it has stopped.  Additionally, the "End Time" attribute is also stuck at some "old" time.  It runs for 24 to 36 hours before getting "stuck"  

There must be a signal from the HA controller that is not interpreted causing it to be "kicked' out of the update process.  Maybe a signal for when the socket disconnects?

Are you having an issue with yours?

**Comment by jdeath** [comment]
Mine is ok. But I restart home assistant pretty often. The update counter should stop at 5, does your go past that? I think it will try to reauthorize 5 times in a row. If your internet is shaky, it may fail quickly. Perhaps throttling the authorize function will help: if self._reauthorize and self._reauthCouter < 5 and "been 10 minutes since last tried":

I can try to play with it in a few days

**Comment by mkmer** [comment]
I added an "update" counter just to know if the update function is being called.  I think I found the "path" where it's getting stuck; IF the access_token is None after a reauth, there is no path to recover (unless I'm missing something).
 I've added an else statement to set reauth true - Time will tell if that fixes it.

if self._access_token is not None: (Needs and else?)

**Comment by jdeath** [comment]
Let me know. If access_token is none, _reauthorize should be true in the authorize function. Then at the next update loop (in 5 minutes), it should try to reauthorize. So it should not get stuck. I probably do not need to variables, but I was lazy.

**Comment by mkmer** [comment]
It appears that the website is not returning a token?
self._access_token = data.get('access_token')

If this code has data that's none, it will not recover (I think).  (data.get() returns none, but "succeeds" without and exception.
That's the only path I can find where the code would stop - as I put my counter inside the if statement, and it stopped counting.

I've added a counter in the added else statement - we'll see if it's getting there and I'll let you know. Let's hope it's that easy.
If it is reaching the else, then data.get() must return none under some condition that doesn't fail the try.

**Comment by mkmer** [comment]
Well... it's definitely the data.get() function.  For whatever reason, the web data dictionary is missing the "access_token" sometimes, and data.get(xxx) does not throw and error, instead it returns "none" and the update function is forever stuck.

Simply added (the line number won't match exactly due to the last part of the comment)

469    else: #No token... try again!
470         self._reauthorize = true

boom, hasn't been stuck since.

Also, had some fun with the unit states.  The nest of ifs can be cleaned up a bit (if you want) 
Create a dictionary "UNIT_STATES"
27               UNIT_STATES = {"0":"Ready",
 28                "1":"Not Running",
 29                "6":"Paused",
 30                "7":"Running",
 31                "8":"Wrinkle Prevent",
 32                "10":"Cycle Complete"
 33               }

Then convert the if logic to:

194              self._state = UNIT_STATES.get(self._status,self._status)

and

428               self._state = UNIT_STATES.get(self._status,self._status)

BTW: no expert here just playing "python" and having a bit of fun.

**Comment by jdeath** [comment]
I’m no expert either. Once you are sure it is solid, can you do a PR? That
would be easiest. Can all be done from web, so don’t need any tools. Just
fork repo, upload your new file to replace the old, and click create PR.

If not, I’ll try to make these changes in the next couple days.

**Comment by mkmer** [comment]
Jdeath,  
 After some major overhaul, I have modified your version to automatically discover SAID's, automatically figure out washer/dryer, and added a config flow for the non HACS HA.  Since it's so modified, I didn't think you would want a PR for this.  Feel free to copy anything from the repo that you like - it's mostly your work.... 
https://github.com/mkmer/whirlpool_laundry

**Comment by jdeath** [comment]
Sounds awesome. I’ll test it out. I’ll Probably just point people to your
repo since your version sounds way cooler and you have the skills to keep
it updated. Thanks for doing this.
