### ISSUE TITLE
Add Load & Go Detergent Status for Whirlpool Washers

### ISSUE THREAD

**Issue by exeljb** [jdeath/maytag_dryer_homeassistant#4]
This integration is great but I noticed that it was missing the status for the automatic detergent dispenser.  My model is a Whirlpool WTW8127LC0.  Maybe this can be added to the integration sometime in the future?

I was able to get some json info that shows:
`        "WashCavity_ChangeStatusBulkDispense1": {
            "value": "0",
            "updateTime": 1644084036749
        },
`
`        "WashCavity_ChangeStatusBulkDispense1Concentration": {
            "value": "0",
            "updateTime": 1644084036742
        },
`
Not sure what these top 2 do right now

`
"WashCavity_CycleSetBulkDispense1Enable": {
            "value": "1",
            "updateTime": 1644618643455
        },
`
This shows if the dispenser mode is active or not.  `1` for yes, `0` for no, `2` for disabled for 1 cycle

`
"WashCavity_OpStatusDispenserDrawerOpen": {
            "value": "0",
            "updateTime": 1645258315408
        },
`
This shows `1` for drawer pulled out for filling, `0` for the drawer inserted.  Edit** This one is already in the current sensor.py

`
"WashCavity_OpStatusBulkDispense1Level": {
            "value": "5",
            "updateTime": 1645258315411
        },
`
I believe that one shows a `1` for empty (also when drawer is pulled out), `5` for 75% level, `3` for 50%, `4` for 100%.  I'm going to have to test the 25% level at another time but I'd guess it would be a `2`

`
"WashCavity_OpSetBulkDispense1Concentration": {
            "value": "10",
            "updateTime": 1644618643452
        },
`
This shows `10` for the '10x' setting, `55` for '2x', `30` for '4x', `20` for '6x', and `15` for '8x'

Here's the full json dump for reference:
`{
    "_id": "WPR**********",
    "applianceId": "WPR**********",
    "lastFullSyncTime": 1621221124027,
    "lastModified": 1645260212916,
    "attributes": {
        "Zip": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "XCat_ApplianceInfoSetSerialNumber": {
            "value": "CA*******",
            "updateTime": 1644084035412
        },
        "Cavity_OpStatusDoorOpen": {
            "value": "0",
            "updateTime": 1645259544337
        },
        "WashCavity_ChangeStatusExtraRinse": {
            "value": "0",
            "updateTime": 1644084036752
        },
        "Cavity_CycleSetSpecialtyCycleId": {
            "value": "0",
            "updateTime": 1644618643410
        },
        "Cavity_CycleStatusMachineState": {
            "value": "1",
            "updateTime": 1645259322243
        },
        "WashCavity_ChangeStatusCycleSelect": {
            "value": "0",
            "updateTime": 1644084036762
        },
        "trid_result": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "ISPReasonCode": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "UtilityID": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "ISP_PART_NUMBER": {
            "value": "W00000000",
            "updateTime": 1644084033283
        },
        "sys-parser-type": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "WashCavity_CycleStatusCleanReminder": {
            "value": "0",
            "updateTime": 1644618643347
        },
        "Cavity_TimeSetDelayTime": {
            "value": "0",
            "updateTime": 1644618643446
        },
        "Sys_DisplaySetLanguage": {
            "value": "0",
            "updateTime": 1644618643416
        },
        "ISP_DownloadEnd": {
            "value": "80",
            "updateTime": 1637215589656
        },
        "version": {
            "value": "1",
            "updateTime": 1644084033489
        },
        "XCat_PersistentInfoVersion": {
            "value": "18",
            "updateTime": 1644084035400
        },
        "trid": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "ISP_UpdateNotification": {
            "value": "16********",
            "updateTime": 1637215589656
        },
        "WashCavity_ChangeStatusDeepFill": {
            "value": "0",
            "updateTime": 1644084036768
        },
        "SetDNSNames": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "XCat_SmartGridStatusSmartGridCompliant": {
            "value": "2",
            "updateTime": 1644084036721
        },
        "WashCavity_CycleSetFabricSoftenerEnable": {
            "value": "0",
            "updateTime": 1645255170477
        },
        "WashCavity_CycleStatusDraining": {
            "value": "0",
            "updateTime": 1644618641843
        },
        "ISP_RebootTime": {
            "value": "0",
            "updateTime": 1637215589656
        },
        "Relational_to_Appliance": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "WashCavity_CycleStatusRinsing": {
            "value": "0",
            "updateTime": 1645257638501
        },
        "XCat_OdometerStatusTotalHours": {
            "value": "6425",
            "updateTime": 1645257638521
        },
        "ISP_InstallEnd": {
            "value": "0",
            "updateTime": 1637215589656
        },
        "ISP_TotalProcessInModule": {
            "value": "1",
            "updateTime": 1637215589656
        },
        "XCat_SmartGridSetSmartGridEnable": {
            "value": "0",
            "updateTime": 1644084036717
        },
        "ISP_CurrentProcessInModule": {
            "value": "0",
            "updateTime": 1637215589656
        },
        "Cavity_TimeStatusDelayTimeRemaining": {
            "value": "0",
            "updateTime": 1644618643341
        },
        "XCat_PersistentInfoSaid": {
            "value": "WPR**********",
            "updateTime": 1644084035409
        },
        "XCat_RemoteSetRemoteControlEnable": {
            "value": "0",
            "updateTime": 1645258066289
        },
        "UtcOffset": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "uid": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "PushTrigger": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "Cavity_TimeStatusEstTimeRemaining": {
            "value": "2340",
            "updateTime": 1645257946199
        },
        "WashCavity_CycleSetPresoakTimed": {
            "value": "0",
            "updateTime": 1644630461048
        },
        "XCat_RemoteSetRebootAppliance": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "Cavity_OpStatusDoorLocked": {
            "value": "0",
            "updateTime": 1645259544334
        },
        "InServiceDate": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "ISP_CurrentModule": {
            "value": "0",
            "updateTime": 1637215589656
        },
        "XCat_PersistentInfoMacAddress": {
            "value": "A8:03:**:**:**:**",
            "updateTime": 1644084035406
        },
        "M2MSubList": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "WashCavity_ChangeStatusBulkDispense1": {
            "value": "0",
            "updateTime": 1644084036749
        },
        "XCat_DateTimeSetDateTimeSet": {
            "value": "2022-02-18T05:18:52-06:00",
            "updateTime": 1645183132397
        },
        "XCat_OdometerStatusCycleCount": {
            "value": "245",
            "updateTime": 1645257638524
        },
        "Online": {
            "value": "1",
            "updateTime": 1644084032886
        },
        "MAC_Address": {
            "value": "A8:03:**:**:**:**",
            "updateTime": 1644084033234
        },
        "ISPBundleAttributes": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "WashCavity_CycleSetSoilLevel": {
            "value": "3",
            "updateTime": 1645255170473
        },
        "ISPStep": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "WashCavity_CycleStatusAddGarment": {
            "value": "0",
            "updateTime": 1645255204984
        },
        "WashCavity_CycleStatusFilling": {
            "value": "0",
            "updateTime": 1645257638486
        },
        "ControlLockChangedByAppliance": {
            "value": "false",
            "updateTime": 1621221124027
        },
        "EnergyProfileSetting": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "Sys_AlertStatusCustomerFaultCode": {
            "value": "F0,E0,0",
            "updateTime": 1644618643331
        },
        "WashCavity_CycleSetExtraRinseSelect": {
            "value": "0",
            "updateTime": 1644618643425
        },
        "WashCavity_CycleSetDeepFillEnable": {
            "value": "2",
            "updateTime": 1645255170481
        },
        "WashCavity_ChangeStatusFabricSoftener": {
            "value": "0",
            "updateTime": 1644084036759
        },
        "WashCavity_ChangeStatusBulkDispense1Concentration": {
            "value": "0",
            "updateTime": 1644084036742
        },
        "GetSubscribeListVersion": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "ModelNumber": {
            "value": "WTW8127LC0",
            "updateTime": 1644084033234
        },
        "WashCavity_CycleStatusSpinning": {
            "value": "0",
            "updateTime": 1645257638509
        },
        "XCat_OdometerStatusRunningHours": {
            "value": "266",
            "updateTime": 1645257638518
        },
        "ProjectReleaseNumber": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "ApplianceVersionNumber": {
            "value": "2",
            "updateTime": 1644084033283
        },
        "ccuri": {
            "value": "API144_LAUNDRY_V18",
            "updateTime": 1644084033234
        },
        "WashCavity_CycleSetBulkDispense1Enable": {
            "value": "2",
            "updateTime": 1645260212585
        },
        "WashCavity_CycleSetSpinSpeed": {
            "value": "4",
            "updateTime": 1644776432706
        },
        "WashCavity_OpStatusDispenserDrawerOpen": {
            "value": "0",
            "updateTime": 1645259541331
        },
        "WashCavity_CycleSetTemperature": {
            "value": "2",
            "updateTime": 1645255179485
        },
        "SerialNumber": {
            "value": "CA*******",
            "updateTime": 1644084033234
        },
        "SmartID": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "WashCavity_ChangeStatusSpinSpeed": {
            "value": "1",
            "updateTime": 1645257638512
        },
        "XCat_WifiStatusRssiAntennaDiversity": {
            "value": "-62",
            "updateTime": 1644084036724
        },
        "WashCavity_CycleStatusCleanDetection": {
            "value": "0",
            "updateTime": 1645257638515
        },
        "XCat_PowerStatusPowerOutage": {
            "value": "0",
            "updateTime": 1637098367785
        },
        "Cavity_CycleSetCycleName": {
            "value": "",
            "updateTime": 1644618643407
        },
        "WashCavity_CycleStatusSoaking": {
            "value": "0",
            "updateTime": 1644618641840
        },
        "WashCavity_ChangeStatusPresoakTimed": {
            "value": "0",
            "updateTime": 1644084036765
        },
        "XCat_WifiSetPublishApplianceState": {
            "value": "false",
            "updateTime": 1621221124027
        },
        "SAID": {
            "value": "WPR**********",
            "updateTime": 1644084033234
        },
        "RatePlanID": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "Cavity_OpSetOperations": {
            "value": "0",
            "updateTime": 1644084036746
        },
        "XCat_SmartGridSetSmartGridMode": {
            "value": "0,0,0,0,0",
            "updateTime": 1644084036738
        },
        "Sys_OpSetAlertToneVolume": {
            "value": "0",
            "updateTime": 1644618643413
        },
        "WashCavity_ChangeStatusSoilLevel": {
            "value": "1",
            "updateTime": 1645257638495
        },
        "DstOffset": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "CustomerFaultCodeNotification": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "XCat_ApplianceInfoSetModelNumber": {
            "value": "WTW8127LC0",
            "updateTime": 1644084035403
        },
        "DateTimeMode": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "WashCavity_ChangeStatusTemperature": {
            "value": "1",
            "updateTime": 1645257638506
        },
        "XCat_ConfigSetMaxCustomCycles": {
            "value": "1",
            "updateTime": 1644084036710
        },
        "WashCavity_OpStatusBulkDispense1Level": {
            "value": "4",
            "updateTime": 1645259541334
        },
        "ISP_REASON_CODE": {
            "value": "0",
            "updateTime": 1637215589646
        },
        "WashCavity_OpSetBulkDispense1Concentration": {
            "value": "10",
            "updateTime": 1645259906305
        },
        "ISP_WIFI_VERSION": {
            "value": "0.0.0",
            "updateTime": 1644084033283
        },
        "WashCavity_CycleStatusDispensing": {
            "value": "0",
            "updateTime": 1644618641836
        },
        "M2MSubscribeListVersion": {
            "value": "0",
            "updateTime": 1621221124027
        },
        "WashCavity_CycleStatusSensing": {
            "value": "0",
            "updateTime": 1645257638493
        },
        "WashCavity_CycleStatusWashing": {
            "value": "0",
            "updateTime": 1645257638504
        },
        "Cavity_CycleSetDownloadAndGo": {
            "value": "0",
            "updateTime": 1644084036730
        },
        "WashCavity_CycleSetCycleSelect": {
            "value": "91",
            "updateTime": 1645255170466
        },
        "ISP_DownloadStart": {
            "value": "1",
            "updateTime": 1637215589656
        },
        "TimeZoneId": {
            "value": "America/Chicago",
            "updateTime": 1645183132397
        },
        "ISP_WIFI_PART_NUMBER": {
            "value": "W11453596",
            "updateTime": 1644084033283
        },
        "ISP_InstallStart": {
            "value": "0",
            "updateTime": 1637215589656
        },
        "GetApplianceVersionNumber": {
            "value": "false",
            "updateTime": 1621221124027
        }
    }
}
`

**Comment by jdeath** [comment]
Yes, I can add those, but I won't have a chance for a bit. Should be easy.
You could try yourself. In the sensor.py in your custom componenets directory add:
self._bulkDispense = data.get('attributes').get('WashCavity_ChangeStatusBulkDispense1', {}).get('value')
and add self._bulkDispense to all the places you see other self._XXX being set or returned.

Then repeat for all other values.
