### ISSUE TITLE
Washer works Dryer does not

### ISSUE THREAD

**Issue by bditter** [jdeath/maytag_dryer_homeassistant#5]
Have the setup in the configuration.ymal

sensor:
  - platform: maytag_dryer
    user: "me@me.com"
    password: "password”
    dryersaids:
      - "WPR4F4B6DBF4F"
    washersaids:
      - "WPR4HJWH3JLD4"

  - platform: template
    sensors:
      washer_temp_setting:
        friendly_name: "Dryer Temperature"
        value_template: "{{ state_attr('sensor.maytag_dryer_wpr4f4b6dbf4f', 'temperature') }}"

I can access the washers attributes but the dryer “Data Update Failed”

I’ve double checked the sails and they are correct.

**Comment by jdeath** [comment]
It is possible that your dryer is not supported. If a device does not have a field I am looking for, the update can crash. You can comment out lines 160-184 of sensor.py , then slowly add in fields you think you want. You may find the field that is causing the crash.

Or you can try the official integration `https://www.home-assistant.io/integrations/whirlpool/` . Someone took most of this code and integrated it directly into homeassistant. It probably handles errors much better and do not need to specify saids.

**Comment by bditter** [comment]
I installed the official version to see if the dryer would respond and it did.

I reinstalled your integration and commented out the lines you suggested and restarted HA.  The dryer still responds with Data Update Failed. The washer still works fine.

I wouldn't be against sharing my credentials along with the said if it would help with troubleshooting.

**Comment by bditter** [comment]
I got it working. It was the "airflow" attribute.

**Comment by jdeath** [comment]
What model do you have? I'll make a note in case anyone else has that problem

**Comment by bditter** [comment]
Dryer Model: MED6230HW1

I was looking at making some modifications for my own installation.
I have and Extra Power setting in my app and on the washer/dryer themselves. 

I tried to get an account for the API but kept getting email not whitelisted.

Would you be willing to share the API documentation or do you see a Extra Power attribute?
