### ISSUE TITLE
Fix for March 2024 Stopped Working

### ISSUE THREAD

**Issue by bditter** [jdeath/maytag_dryer_homeassistant#6]
Has anyone reported issues with this or the official integration? Today both stripped working and I get no response from this intervention and “invalid authentication” from the official version. 

Makes me wonder if the API has been changed or if they Whirlpool/Maytag is having issues.

**Comment by jdeath** [comment]
Yup. Same here. Hoping not an API change. 

API is still up and looks fine. Not sure why Home Assistant is having issues. Working on it.

Login works fine from python, but get forbidden from same code in homeassistant....

Their new app seems to work with amazon, and not use the old login API. Will take a better coder than me to figure out

**Comment by jdeath** [comment]
Revert to version 1.0 and it works. Something about the async calls is keeping the old API from working.

**Comment by jdeath** [comment]
Fix added to v1.2 . thanks @mkmer
